# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: "Sam", username: "sam", password: "samsam")

Garden.create(name: "SammyBoy's Garden", user_id: 1)

Plant.create!(name: "Rose", species: "Rose", price: 15.99, image: "pink-red-roses.jpg")
  Plant.create!(name: "Carnation", species: "Carnation", price: 7.99, image: "carnation.jpg")
  
  Plant.create!(name: "Daffodil", species: "Daffodil", price: 4.99, image: "daffodil.jpg")
  Plant.create!(name: "Chrysanthemum", species: "Chrysanthemum", price: 3.99, image: "chrysanthemums.jpg")
  Plant.create!(name: "Marigold", species: "Marigold", price: 10.99, image: "yellow-marigold.jpg")
  Plant.create!(name: "Iris", species: "Iris", price: 17.99, image: "yellow-iris-flower.jpg")
  Plant.create!(name: "Daisy", species: "Daisy", price: 10.99, image: "white-daisy.jpg")
  Plant.create!(name: "Lily", species: "Lily", price: 4.99, image: "pink-lily.jpg")
  Plant.create!(name: "Sunflower", species: "Sunflower", price: 3.99, image: "sunflowers.jpg")
  Plant.create!(name: "Hyacinth", species: "Hyacinth", price: 3.99, image: "blue-hyacinth.jpg")
  Plant.create!(name: "Buttercup", species: "Buttercup", price: 22.25, image: "buttercup-flower.jpg")
  Plant.create!(name: "Hibiscus", species: "Hibiscus", price: 8.25, image: "blue-hibiscus-1.jpg")
  Plant.create!(name: "Aster", species: "Aster", price: 20.99, image: "pink-asters.jpg")
  Plant.create!(name: "Geranium", species: "Geranium", price: 9.99, image: "pink-white-geranium.jpg")
  Plant.create!(name: "Petunia", species: "Petunia", price: 10.99, image: "purple-petunia.jpg")
  Plant.create!(name: "Bletilla", species: "Bletilla", price: 7.99, image: "bletilla.jpg")
  Plant.create!(name: "Orchid", species: "Orchid", price: 4.99, image: "dotted-pink-cattleya.jpg")
  Plant.create!(name: "Hydrangea", species: "Hydrangea", price: 5.99, image: "blue-hydrangea.jpg")
  Plant.create!(name: "Peony", species: "Peony", price: 5.99, image: "pink-peony.jpg")
  Plant.create!(name: "Begonia", species: "Begonia", price: 7.99, image: "pink-begonia.jpg")
  Plant.create!(name: "Carnation", species: "Carnation", price: 6.99, image: "carnation.jpg")
  Plant.create!(name: "Calla Lily", species: "Calla Lily", price: 4.99, image: "calla-lily.jpg")
  Plant.create!(name: "African Daisy", species: "African Daisy", price: 5.99, image: "african-daisy.jpg")
  Plant.create!(name: "Lavender", species: "Lavender", price: 7.99, image: "lavender.jpg")
  Plant.create!(name: "Anemone", species: "Anemone", price: 3.25, image: "anemone.jpg")
  Plant.create!(name: "Candytuft", species: "Candytuft", price: 8.25, image: "candytuft.jpg")
  Plant.create!(name: "Catmint", species: "Lavender", price: 5.25, image: "catmint.jpg")
  Plant.create!(name: "Nasturtium", species: "Nasturtium", price: 9.99, image: "orange-nasturtium-flowers.jpg")
  Plant.create!(name: "Oleander", species: "Oleander", price: 14.25, image: "pink-oleander.jpg")
  Plant.create!(name: "Penstemon", species: "Penstemon", price: 7.99, image: "red-penstemon.jpg")
  Plant.create!(name: "Pinks", species: "Pinks", price: 6.99, image: "pink-dianthus.jpg")
  Plant.create!(name: "Quaker Ladies", species: "Quaker Ladies", price: 3.99, image: "quaker-ladies.jpg")
  Plant.create!(name: "Sage", species: "Sage", price: 8.99, image: "sage-flower-1.jpg")