# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(name: "Sam", username: "sam", password: "samsam")

Garden.create(name: "Garden", user_id: 1)

Plant.create!(name: "Rose", species: "Rose", price: 150, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-red-roses.jpg")
  Plant.create!(name: "Tulip", species: "Tulip", price: 1000, image: "https://florgeous.com/wp-content/uploads/2019/11/pink-purple-tulips.jpg")
  Plant.create!(name: "Carnation", species: "Carnation", price: 750, image: "https://florgeous.com/wp-content/uploads/2019/10/carnation.jpg")
  
  Plant.create!(name: "Daffodil", species: "Daffodil", price: 400, image: "https://florgeous.com/wp-content/uploads/2019/10/daffodil.jpg")
  Plant.create!(name: "Chrysanthemum", species: "Chrysanthemum", price: 300, image: "https://florgeous.com/wp-content/uploads/2019/10/chrysanthemums.jpg")
  Plant.create!(name: "Marigold", species: "Marigold", price: 1000, image: "https://florgeous.com/wp-content/uploads/2019/10/yellow-marigold.jpg")
  Plant.create!(name: "Iris", species: "Iris", price: 175, image: "https://florgeous.com/wp-content/uploads/2019/10/yellow-iris-flower.jpg")
  Plant.create!(name: "Daisy", species: "Daisy", price: 1000, image: "https://florgeous.com/wp-content/uploads/2019/10/white-daisy.jpg")
  Plant.create!(name: "Lily", species: "Lily", price: 450, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-lily.jpg")
  Plant.create!(name: "Sunflower", species: "Sunflower", price: 30, image: "https://florgeous.com/wp-content/uploads/2019/10/sunflowers.jpg")
  Plant.create!(name: "Hyacinth", species: "Hyacinth", price: 350, image: "https://florgeous.com/wp-content/uploads/2019/10/blue-hyacinth.jpg")
  Plant.create!(name: "Buttercup", species: "Buttercup", price: 222, image: "https://florgeous.com/wp-content/uploads/2019/10/buttercup-flower.jpg")
  Plant.create!(name: "Hibiscus", species: "Hibiscus", price: 825, image: "https://florgeous.com/wp-content/uploads/2019/10/blue-hibiscus-1.jpg")
  Plant.create!(name: "Aster", species: "Aster", price: 200, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-asters.jpg")
  Plant.create!(name: "Geranium", species: "Geranium", price: 900, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-white-geranium.jpg")
  Plant.create!(name: "Petunia", species: "Petunia", price: 100, image: "https://florgeous.com/wp-content/uploads/2019/10/purple-petunia.jpg")
  Plant.create!(name: "Bletilla", species: "Bletilla", price: 75, image: "https://florgeous.com/wp-content/uploads/2019/10/bletilla.jpg")
  Plant.create!(name: "Orchid", species: "Orchid", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/dotted-pink-cattleya.jpg")
  Plant.create!(name: "Hydrangea", species: "Hydrangea", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/blue-hydrangea.jpg")
  Plant.create!(name: "Peony", species: "Peony", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-peony.jpg")
  Plant.create!(name: "Begonia", species: "Begonia", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-begonia.jpg")
  Plant.create!(name: "Carnation", species: "Carnation", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/carnation.jpg")
  Plant.create!(name: "Calla Lily", species: "Calla Lily", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/calla-lily.jpg")
  Plant.create!(name: "African Daisy", species: "African Daisy", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/african-daisy.jpg")
  Plant.create!(name: "Lavender", species: "Lavender", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/lavender.jpg")
  Plant.create!(name: "Anemone", species: "Anemone", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/anemone.jpg")
  Plant.create!(name: "Candytuft", species: "Candytuft", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/candytuft.jpg")
  Plant.create!(name: "Catmint", species: "Lavender", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/catmint.jpg")
  Plant.create!(name: "Nasturtium", species: "Nasturtium", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/09/orange-nasturtium-flowers.jpg")
  Plant.create!(name: "Oleander", species: "Oleander", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-oleander.jpg")
  Plant.create!(name: "Penstemon", species: "Penstemon", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/red-penstemon.jpg")
  Plant.create!(name: "Pinks", species: "Pinks", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/pink-dianthus.jpg")
  Plant.create!(name: "Quaker Ladies", species: "Quaker Ladies", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/quaker-ladies.jpg")
  Plant.create!(name: "Sage", species: "Sage", price: 420, image: "https://florgeous.com/wp-content/uploads/2019/10/sage-flower.jpg")